# fly.toml app configuration file generated for pixvault-frontend on 2024-01-21T17:01:37+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "pixvault-frontend"
primary_region = "sin"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024

[env]
  VITE_AUTH0_DOMAIN = "dev-xxxvdv1hc0imt7mz.us.auth0.com"
  VITE_AUTH0_AUDIENCE = "https://dev-xxxvdv1hc0imt7mz.us.auth0.com/api/v2/"
  VITE_AUTH0_CLIENTID = "w2BKsGb3y8eBBckYafX3dWOIj4YNdVhb"
  VITE_SERVER_URL = "https://pixvault-backend.fly.dev"
